version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    network_mode: host
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/pierrick/ContainersData/portainer-data:/data
    ports:
      - 9000:9000
  # sonarr:
  #   image: lscr.io/linuxserver/sonarr:latest
  #   container_name: sonarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/New_York
  #   volumes:
  #     - /opt/docker/data/sonarr:/config
  #     - /media/TV:/media/TV
  #     - /data:/data
  #   ports:
  #     - 8989:8989
  #   restart: unless-stopped
  # radarr:
  #   image: lscr.io/linuxserver/radarr:latest
  #   container_name: radarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/New_York
  #   volumes:
  #     - /opt/docker/data/radarr:/config
  #     - /media/Movies:/media/Movies
  #     - /data:/data
  #   ports:
  #     - 7878:7878
  #   restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /opt/docker/data/plex:/config
      - /media/films/Movies:/media/Movies
      - /media/films/Shows:/media/TV
    restart: unless-stopped
